version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: hanghae-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: hanghae_db
      MYSQL_USER: hanghae_user
      MYSQL_PASSWORD: hanghae1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - hanghae-network

  app:
    build: .
    container_name: hanghae-app
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=hanghae_db
      - DB_USERNAME=hanghae_user
      - DB_PASSWORD=hanghae1234
      - DB_LOGGING_ENABLED=true
      - NODE_ENV=development
    depends_on:
      - mysql
    networks:
      - hanghae-network

volumes:
  mysql_data:

networks:
  hanghae-network:
    driver: bridge 